### ISSUE TITLE
Renderer in line 131 is trying to access "attrs" as an object instead of as an array

### ISSUE THREAD

**Issue by studiosi** [gschoppe/Better-Shortcode-Parser#1]
The line 131  on the renderer should be changed from

`return apply_filters( 'do_shortcode_tag', $output, $tag, $shortcode->attrs, $content, $shortcode );` 

to

`return apply_filters( 'do_shortcode_tag', $output, $tag, $shortcode['attrs'], $content, $shortcode );`

otherwise it does not work. The rest of the code access it as an array. I guess this goes invisible if you don't have debug enabled on the Wordpress installation and you don't use the filter, as it is a warning.

I can do a pull request if I am not mistaken with this. I have tested it already though.

**Comment by gschoppe** [comment]
you are, of course, correct. I had waffled between using a class or an array to manage shortcodes and eventually decided that an array would be more flexible for plugins to add onto in the future, but I didn't refactor that line.
